### ISSUE TITLE
`requestContact` handler callback doesn't works

### ISSUE THREAD

**Issue by kitsuniru** [xooniverse/televerse#288]
Hi! `requestContact` in `KeyboardMenu` doesn't works, it just ignores handler callback and does literally nothing

```dart
import 'package:televerse/televerse.dart';

void main(List<String> arguments) async {
  final bot = Bot('___', loggerOptions: LoggerOptions());

  bot.command("start", (ctx) async {
    final menu = KeyboardMenu(
      resizeKeyboard: true,
      oneTimeKeyboard: true,
    ).requestContact("Send my number", (ctx) {
    // These ignored
      final phone = ctx.message?.contact?.phoneNumber;
    // These ignored
      print('Got number: $phone');

    });

    await ctx.reply(
      "Halo!",
      replyMarkup: menu,
    );
  });

  await bot.start();
}
```

**Comment by kitsuniru** [comment]
Expectation:
1) "Halo!" arrives with a keyboard (+)
2) We press on "Send my number" (+)
3) Number sended and printed out in logs (-)

**Comment by HeySreelal** [comment]
Hey, thanks for bringing this up. I'll investigate this quickly and get back to you as soon as I can. Thanks :)

**Comment by HeySreelal** [comment]
Yep, I'm back :)

I just tried your code. Actually, there's a small mistake or I should say one line that you've missed.

For menus to work - I mean to make them interactive, you should attach the menu to your bot. Here's how to:

```dart
  bot.attachMenu(menu);
```

So, in best practice your code should be something like:

```dart
import 'dart:io';
import 'package:televerse/televerse.dart';

void main(List<String> arguments) async {
  final bot = Bot(
    Platform.environment["BOT_TOKEN"]!,
    loggerOptions: LoggerOptions(),
  );

  final menu = KeyboardMenu(
    resizeKeyboard: true,
    oneTimeKeyboard: true,
  ).requestContact("Send my number", (ctx) {
    final phone = ctx.message?.contact?.phoneNumber;
    print('Got number: $phone');
  });

  bot.attachMenu(menu);

  bot.command("start", (ctx) async {
    await ctx.reply(
      "Halo!",
      replyMarkup: menu,
    );
  });

  await bot.start();
}
```

## Why?

Creating and attaching menu inside handlers can sometimes cause to memory leaks - as they would be created every time the "start" handler is called.

Hope this helps :)

**Comment by HeySreelal** [comment]
Btw, just bringing to your attention, please feel free to join our [Telegram group](https://telegram.me/televersedart) if you're stuck at any point with your bot development - you're most likely to get your questions answered much quicker there. (Completely optional, but feel free to).

Happy Televersing! 🚀

**Comment by kitsuniru** [comment]
Yeah, that works, thank you!
