### ISSUE TITLE
Markdown / html docs

### ISSUE THREAD

**Issue by zubbyy** [xooniverse/televerse#296]
Hey, i was setting up my bot and couldn't see anywhere in the documentation how to use bold text or markdown support in general. i think i've seen an implementation [here](https://github.com/xooniverse/televerse/issues/65) tho.
thanks

**Comment by HeySreelal** [comment]
Hey, thanks for raising this :)

Actually we support [all the formatting specs Telegram allows](https://core.telegram.org/bots/api#formatting-options) - this includes `Markdown`, `HTML`, and `MarkdownV2`.

You'll just have to specify the `parseMode` parameter in the methods you use. Here's an example:

```dart
  bot.command("start", (ctx) async {
    await ctx.reply("*Bolded Hello*", parseMode: ParseMode.markdown);
  });

  bot.command("html", (ctx) async {
    await ctx.reply("<b>Bolded Hello with HTML</b>", parseMode: ParseMode.html);
  });
```
Hope this helps! 

---
_By the way, we have a Telegram chat ([@TeleverseDart](https://telegram.me/televersedart)) - I suppose you're likely to get answers much quicker there, just FYI - if you're feeling lucky feel free to jump in :)_
